name: DNAnexus Applet Build Action
description: Automates building a DNAnexus applet
author: Kurt Mueller
inputs: 
  api-token:
    description: Your DNAnexus API Token
    required: true
  project:
    description: The project name or id
    required: true
  force:
    description: Override any existing applet
    required: false
    default: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.api-token }}
    - ${{ inputs.project }}
    - ${{ inputs.force }}
